# Generated by Django 5.1 on 2024-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_avatar',
            field=models.ImageField(blank=True, default='images/logo3.svg', upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='images/logo5.PNG', upload_to='uploads/post_images'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_pic',
            field=models.ImageField(blank=True, default='quote/pics/logo2.svg', upload_to='quote/pics'),
        ),
    ]
