# Generated by Django 5.1 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_alter_blogpost_author_avatar_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_avatar',
            field=models.ImageField(blank=True, default='images/logo3.png', upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_pic',
            field=models.ImageField(blank=True, default='images/logo2.png', upload_to='quote/pics'),
        ),
    ]
