from django.core.management.base import BaseCommand
from clients.models import Country, State, City

class Command(BaseCommand):
    help = 'Populate the database with initial data for countries, states. and cities'

    def handle(self, *args, **kwargs):
        countries = [
            {"name": "Ghana"},
            {"name": "Nigeria"},
            {"name": "South Africa"},
            {"name": "Togo"}
        ]

        states = [
            {"name": "Campari", "country": "Togo"},
            {"name": "Cape Town", "country": "South Africa"},
            {"name": "Accra", "country": "Ghana"},
            {"name": "Abia", "country": "Nigeria"},
            {"name": "Adamawa", "country": "Nigeria"},
            {"name": "Akwa-Ibom", "country": "Nigeria"},
            {"name": "Anambra", "country": "Nigeria"},
            {"name": "Bauchi", "country": "Nigeria"},
            {"name": "Bayelsa", "country": "Nigeria"},
            {"name": "Benue", "country": "Nigeria"},
            {"name": "Borno", "country": "Nigeria"},
            {"name": "Cross-River", "country": "Nigeria"},
            {"name": "Delta", "country": "Nigeria"},
            {"name": "Ebonyi", "country": "Nigeria"},
            {"name": "Edo", "country": "Nigeria"},
            {"name": "Ekiti", "country": "Nigeria"},
            {"name": "Enugu", "country": "Nigeria"},
            {"name": "FCT", "country": "Nigeria"},
            {"name": "Gombe", "country": "Nigeria"},
            {"name": "Imo", "country": "Nigeria"},
            {"name": "Jigawa", "country": "Nigeria"},
            {"name": "Kaduna", "country": "Nigeria"},
            {"name": "Kano", "country": "Nigeria"},
            {"name": "Katsina", "country": "Nigeria"},
            {"name": "Kebbi", "country": "Nigeria"},
            {"name": "Kogi", "country": "Nigeria"},
            {"name": "Kwara", "country": "Nigeria"},
            {"name": "Lagos", "country": "Nigeria"},
            {"name": "Nasarawa", "country": "Nigeria"},
            {"name": "Niger", "country": "Nigeria"},
            {"name": "Ogun", "country": "Nigeria"},
            {"name": "Ondo", "country": "Nigeria"},
            {"name": "Osun", "country": "Nigeria"},
            {"name": "Oyo", "country": "Nigeria"},
            {"name": "Plateau", "country": "Nigeria"},
            {"name": "Rivers", "country": "Nigeria"},
            {"name": "Sokoto", "country": "Nigeria"},
            {"name": "Taraba", "country": "Nigeria"},
            {"name": "Yobe", "country": "Nigeria"},
            {"name": "Zamfara", "country": "Nigeria"},
            {"name": "Johanesburg", "country": "South Africa"}
            
        ]

        cities = [
            {"name": "Aba", "state": "Abia"},
            {"name": "Arochukwu", "state": "Abia"},
            {"name": "Umuahia", "state": "Abia"},
            {"name": "Jimeta", "state": "Adamawa"},
            {"name": "Mubi", "state": "Adamawa"},
            {"name": "Numan", "state": "Adamawa"},
            {"name": "Yola", "state": "Adamawa"},
            {"name": "Ikot Abasi", "state": "Akwa-Ibom"},
            {"name": "Ikot Ekpene", "state": "Akwa-Ibom"},
            {"name": "Oron", "state": "Akwa-Ibom"},
            {"name": "Uyo", "state": "Akwa-Ibom"},
            {"name": "Awka", "state": "Anambra"},
            {"name": "Onitsha", "state": "Anambra"},
            {"name": "Azare", "state": "Bauchi"},
            {"name": "Bauchi", "state": "Bauchi"},
            {"name": "Jama`are", "state": "Bauchi"},
            {"name": "Katagum", "state": "Bauchi"},
            {"name": "Misau", "state": "Bauchi"},
            {"name": "Brass", "state": "Bayelsa"},
            {"name": "Yenegoa", "state": "Bayelsa"},
            {"name": "Makurdi", "state": "Benue"},
            {"name": "Biu", "state": "Borno"},
            {"name": "Dikwa", "state": "Borno"},
            {"name": "Maiduguri", "state": "Borno"},
            {"name": "Calabar", "state": "Cross-River"},
            {"name": "Ogoja", "state": "Cross-River"},
            {"name": "Asaba", "state": "Delta"},
            {"name": "Burutu", "state": "Delta"},
            {"name": "Koko", "state": "Delta"},
            {"name": "Sapele", "state": "Delta"},
            {"name": "Ughelli", "state": "Delta"},
            {"name": "Warri", "state": "Delta"},
            {"name": "Abakaliki", "state": "Ebonyi"},
            {"name": "Benin City", "state": "Edo"},
            {"name": "Ado-Ekiti", "state": "Ekiti"},
            {"name": "Effon-Alaiye", "state": "Ekiti"},
            {"name": "Ikere-Ekiti", "state": "Ekiti"},
            {"name": "Enugu", "state": "Enugu"},
            {"name": "Nsukka", "state": "Enugu"},
            {"name": "Emene", "state": "Enugu"},
            {"name": "Nike", "state": "Enugu"},
            {"name": "Abuja", "state": "FCT"},
            {"name": "Deba Habe", "state": "Gombe"},
            {"name": "Gombe", "state": "Gombe"},
            {"name": "Kumo", "state": "Gombe"},
            {"name": "Owerri", "state": "Imo"},
            {"name": "Birnin Kudu", "state": "Jigawa"},
            {"name": "Dutse", "state": "Jigawa"},
            {"name": "Gumel", "state": "Jigawa"},
            {"name": "Hadejia", "state": "Jigawa"},
            {"name": "Kazaure", "state": "Jigawa"},
            {"name": "Kano", "state": "Kano"},
            {"name": "Daura", "state": "Katsina"},
            {"name": "Katsina", "state": "Katsina"},
            {"name": "Argungu", "state": "Kebbi"},
            {"name": "Birnin Kebbi", "state": "Kebbi"},
            {"name": "Gwandu", "state": "Kebbi"},
            {"name": "Yelwa", "state": "Kebbi"},
            {"name": "Idah", "state": "Kogi"},
            {"name": "Kabba", "state": "Kogi"},
            {"name": "Okene", "state": "Kogi"},
            {"name": "Lokoja", "state": "Kogi"},
            {"name": "Ilorin", "state": "Kwara"},
            {"name": "Jebba", "state": "Kwara"},
            {"name": "Lafiagi", "state": "Kwara"},
            {"name": "Offa", "state": "Kwara"},
            {"name": "Pategi", "state": "Kwara"},
            {"name": "Badagry", "state": "Lagos"},
            {"name": "Epe", "state": "Lagos"},
            {"name": "Ikeja", "state": "Lagos"},
            {"name": "Ikorodu", "state": "Lagos"},
            {"name": "Lagos", "state": "Lagos"},
            {"name": "Mushin", "state": "Lagos"},
            {"name": "Shomolu", "state": "Lagos"},
            {"name": "Lekki", "state": "Lagos"},
            {"name": "Keffi", "state": "Nasarawa"},
            {"name": "Lafia", "state": "Nasarawa"},
            {"name": "Nasarawa", "state": "Nasarawa"},
            {"name": "Agaie", "state": "Niger"},
            {"name": "Baro", "state": "Niger"},
            {"name": "Bida", "state": "Niger"},
            {"name": "Kontagora", "state": "Niger"},
            {"name": "Lapai", "state": "Niger"},
            {"name": "Minna", "state": "Niger"},
            {"name": "Suleja", "state": "Niger"},
            {"name": "Abeokuta", "state": "Ogun"},
            {"name": "Ijebu-Ode", "state": "Ogun"},
            {"name": "Ilaro", "state": "Ogun"},
            {"name": "Shagamu", "state": "Ogun"},
            {"name": "Akure", "state": "Ondo"},
            {"name": "Ikare", "state": "Ondo"},
            {"name": "Oka-Akoko", "state": "Ondo"},
            {"name": "Ondo", "state": "Ondo"},
            {"name": "Owo", "state": "Ondo"},
            {"name": "Ede", "state": "Osun"},
            {"name": "Ikire", "state": "Osun"},
            {"name": "Ikirun", "state": "Osun"},
            {"name": "Ila", "state": "Osun"},
            {"name": "Ile-Ife", "state": "Osun"},
            {"name": "Ilesha", "state": "Osun"},
            {"name": "Ilobu", "state": "Osun"},
            {"name": "Inisa", "state": "Osun"},
            {"name": "Iwo", "state": "Osun"},
            {"name": "Oshogbo", "state": "Osun"},
            {"name": "Ibadan", "state": "Oyo"},
            {"name": "Iseyin", "state": "Oyo"},
            {"name": "Ogbomosho", "state": "Oyo"},
            {"name": "Oyo", "state": "Oyo"},
            {"name": "Saki", "state": "Oyo"},
            {"name": "Bukuru", "state": "Plateau"},
            {"name": "Jos", "state": "Plateau"},
            {"name": "Vom", "state": "Plateau"},
            {"name": "Wase", "state": "Plateau"},
            {"name": "Bonny", "state": "Rivers"},
            {"name": "Degema", "state": "Rivers"},
            {"name": "Okrika", "state": "Rivers"},
            {"name": "Port Harcourt", "state": "Rivers"},
            {"name": "Sokoto", "state": "Sokoto"},
            {"name": "Ibi", "state": "Taraba"},
            {"name": "Jalingo", "state": "Taraba"},
            {"name": "Muri", "state": "Taraba"},
            {"name": "Damaturu", "state": "Yobe"},
            {"name": "Nguru", "state": "Yobe"},
            {"name": "Gusau", "state": "Zamfara"},
            {"name": "Kaura Namoda", "state": "Zamfara"}

        ]

        for country in countries:
            Country.objects.get_or_create(name=country['name'])

        for state in states:
            country = Country.objects.get(name=state['country'])
            State.objects.get_or_create(name=state['name'], country=country)

        for city in cities:
            state = State.objects.get(name=city['state'])
            City.objects.get_or_create(name=city['name'], state=state)    

        self.stdout.write(self.style.SUCCESS('Successfully populated the database')) 

        # Run the command: python manage.py populate_locations    